Repository ucsb-cs156-w24/proj-organic-w24-6pm-3, pull requests merged in 2024-03, with the labels that each got.

#35 Jw iconbug
  frontend/public/favicon.ico
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/src/fixtures/currentUserFixtures.js
Labels: FIXME - Peer CR

#37 KV - BUG Courses Start Date cannot be before the End date
  frontend/src/main/components/Courses/CoursesForm.js
  frontend/src/tests/components/Courses/CoursesForm.test.js
  frontend/src/tests/pages/CoursesEditPage.test.js
Labels: 5

#38 TP - Added Join Button
  frontend/src/main/components/Courses/CoursesTable.js
  frontend/src/tests/components/Courses/CoursesTable.test.js
Labels: 5

#39 AJ - [Fix] Fixed default date bug in userprofile page
  frontend/src/main/utils/dateUtils.js
  frontend/src/tests/utils/dateUtils.test.js
Labels: 5

#36 JL - Bug Admin can Toggle Their Admin Rights Of
  frontend/src/fixtures/usersFixtures.js
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/main/pages/AdminUsersPage.js
  frontend/src/tests/components/Users/UsersTable.test.js
  frontend/src/tests/pages/AdminUsersPage.test.js
Labels: 10

#40 JL - FEATURE Popups for Admin Toggles
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/tests/components/Users/UsersTable.test.js
  frontend/src/tests/pages/AdminUsersPage.test.js
Labels: 10

#41 Jw feature course
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/CourseIndexPage.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/CourseIndexPage.test.js
Labels: 10

#42 AJ - Create Staff Button
  frontend/src/main/components/Courses/CoursesTable.js
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/tests/components/Courses/CoursesTable.test.js
Labels: 5

#43 TP - instructors create course
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
  src/test/java/edu/ucsb/cs156/organic/controllers/CoursesControllerTests.java
Labels: 5
